// @generated by `pnpm fate generate`
import type { AppRouter } from '@app/api/src/trpc/app-router.ts';
import { createTRPCProxyClient } from '@trpc/client';
import type { inferRouterInputs, inferRouterOutputs } from '@trpc/server';
import { clientRoot, createClient, createTRPCTransport, mutation } from 'react-fate';

type TRPCClientType = ReturnType<typeof createTRPCProxyClient<AppRouter>>;
type RouterInputs = inferRouterInputs<AppRouter>;
type RouterOutputs = inferRouterOutputs<AppRouter>;

const mutations = {

} as const;

const roots = {
  'post': clientRoot<RouterOutputs['post']['byId'], 'Post'>('Post'),
  'posts': clientRoot<RouterOutputs['post']['list'], 'Post'>('Post'),
  'project': clientRoot<RouterOutputs['project']['project'], 'Project'>('Project'),
} as const;

type GeneratedClientMutations = typeof mutations;
type GeneratedClientRoots = typeof roots;

declare module 'react-fate' {
  interface ClientMutations extends GeneratedClientMutations {}
  interface ClientRoots extends GeneratedClientRoots {}
}

export const createFateClient = (options: {
  links: Parameters<typeof createTRPCProxyClient>[0]['links'];
}) => {
  const trpcClient = createTRPCProxyClient<AppRouter>(options);

  const trpcMutations = {

  } as const;

  return createClient<[GeneratedClientRoots, GeneratedClientMutations]>({
    mutations,
    roots,
    transport: createTRPCTransport<AppRouter, typeof trpcMutations>({
      byId: {
        Post: (client: TRPCClientType) => ({
          args,
          ids,
          select,
        }: { args?: Record<string, unknown>; ids: Array<string | number>; select: Array<string> }) =>
          client.post.byId.query({
            args,
            ids: ids.map(String),
            select,
          }),
      },
      client: trpcClient,
      queries: {
        project: (client: TRPCClientType) => client.project.project.query,
      },
      lists: {
        posts: (client: TRPCClientType) => client.post.list.query,
      },
      mutations: trpcMutations,
    }),
    types: [
        {
          type: 'Post',
        },
        {
          type: 'Project',
        },
      ],
  });
};
