// @generated by `pnpm fate generate`
import type { AppRouter, ServiceInstance } from "@app/api/src/trpc/app-router.ts";
import { createTRPCProxyClient } from "@trpc/client";
import type { inferRouterInputs, inferRouterOutputs } from "@trpc/server";
import { clientRoot, createClient, createTRPCTransport, mutation } from "react-fate";

type TRPCClientType = ReturnType<typeof createTRPCProxyClient<AppRouter>>;
type RouterInputs = inferRouterInputs<AppRouter>;
type RouterOutputs = inferRouterOutputs<AppRouter>;

const mutations = {
  "serviceInstance.deploymentRemove": mutation<
    ServiceInstance,
    RouterInputs["serviceInstance"]["deploymentRemove"],
    RouterOutputs["serviceInstance"]["deploymentRemove"]
  >("ServiceInstance"),
  "serviceInstance.enableServerless": mutation<
    ServiceInstance,
    RouterInputs["serviceInstance"]["enableServerless"],
    RouterOutputs["serviceInstance"]["enableServerless"]
  >("ServiceInstance"),
  "serviceInstance.redeploy": mutation<
    ServiceInstance,
    RouterInputs["serviceInstance"]["redeploy"],
    RouterOutputs["serviceInstance"]["redeploy"]
  >("ServiceInstance"),
  "serviceInstance.sync": mutation<ServiceInstance, RouterInputs["serviceInstance"]["sync"], RouterOutputs["serviceInstance"]["sync"]>(
    "ServiceInstance",
  ),
  "serviceInstance.updateReplicas": mutation<
    ServiceInstance,
    RouterInputs["serviceInstance"]["updateReplicas"],
    RouterOutputs["serviceInstance"]["updateReplicas"]
  >("ServiceInstance"),
} as const;

const roots = {
  environment: clientRoot<RouterOutputs["environment"]["environment"], "Environment">("Environment"),
  project: clientRoot<RouterOutputs["project"]["project"], "Project">("Project"),
} as const;

type GeneratedClientMutations = typeof mutations;
type GeneratedClientRoots = typeof roots;

declare module "react-fate" {
  interface ClientMutations extends GeneratedClientMutations {}
  interface ClientRoots extends GeneratedClientRoots {}
}

export const createFateClient = (options: { links: Parameters<typeof createTRPCProxyClient>[0]["links"] }) => {
  const trpcClient = createTRPCProxyClient<AppRouter>(options);

  const trpcMutations = {
    "serviceInstance.deploymentRemove": (client: TRPCClientType) => client.serviceInstance.deploymentRemove.mutate,
    "serviceInstance.enableServerless": (client: TRPCClientType) => client.serviceInstance.enableServerless.mutate,
    "serviceInstance.redeploy": (client: TRPCClientType) => client.serviceInstance.redeploy.mutate,
    "serviceInstance.sync": (client: TRPCClientType) => client.serviceInstance.sync.mutate,
    "serviceInstance.updateReplicas": (client: TRPCClientType) => client.serviceInstance.updateReplicas.mutate,
  } as const;

  return createClient<[GeneratedClientRoots, GeneratedClientMutations]>({
    mutations,
    roots,
    transport: createTRPCTransport<AppRouter, typeof trpcMutations>({
      byId: {},
      client: trpcClient,
      queries: {
        // @ts-expect-error - fate is still in beta
        environment: (client: TRPCClientType) => client.environment.environment.query,
        // @ts-expect-error - fate is still in beta
        project: (client: TRPCClientType) => client.project.project.query,
      },
      mutations: trpcMutations,
    }),
    types: [
      {
        type: "Service",
      },
      {
        type: "Deployment",
      },
      {
        fields: {
          service: { type: "Service" },
          latestDeployment: { type: "Deployment" },
        },
        type: "ServiceInstance",
      },
      {
        fields: {
          serviceInstances: { listOf: "ServiceInstance" },
        },
        type: "Environment",
      },
      {
        fields: {
          environments: { listOf: "Environment" },
        },
        type: "Project",
      },
    ],
  });
};
